### ISSUE TITLE
Xcode 8.2 and Swift

### ISSUE THREAD

**Issue by beneiltis** [TimOliver/TOSMBClient#42] opened 2017-01-20 06:03 UTC
When I try to install (cocoapods 1.1.0) your Lib on Xcode 8.2 (using swift 3.0.1) I receive an error saying "Could not build Objective-C module 'TOSMBClient' when I try to import "import TOSMBClient". 
I also tried to add a Bridging Header without success. But as I can see, you already integrated this into the lib.

Of course I cleared "derivedData", did clean and all the other std. stuff :-)

Do you have any advices?

**Comment by tmrbaset** [comment] 2017-01-29 02:18
I have the same issue here, exactly same details.

hopefully someone can help.

**Comment by beks6** [comment] 2017-04-16 22:34
Didn't wanted to open a new issue.

Completely new to iOS dev and need some help how to add this library to my Swift project. Would like to upload some images to a SMB Fileshare and also create folders

Any help is appreciated

**Comment by beks6** [comment] 2017-04-18 20:48
OK, I think I figured it out.

@beneiltis @tmrbaset  

Step by step what I did:

Installed TOSMBClient (1.0.5) with cocoapods into my testing project. After first try I got a "file not found" error. This is due to a misinterpretation or linking/finding the bdsm.h file

You need to manually fix the linkings

Change `#include "bdsm/netbios_ns.h"` to `#include "netbios_ns.h"` and do it for all rows in this file

After that change I got a new error, "expected type" in TONetBIOSNameServiceType.h in rows 48 and 59.

To resolve this issue you have to go to Pods project -> Build Phase on the left side choose TOSMBClient under Targets tab. Then change the order of the files when they are compiled. This is my order which works for my project

![bildschirmfoto 2017-04-18 um 22 36 24](https://cloud.githubusercontent.com/assets/6977103/25151893/88396382-2487-11e7-94da-36c9e9b3cc88.png)

I also adapted the following file to the same order

TOSMBClient-umbrella.h


After these adaptions I'm now able to import TOSMBClient to my Swift project. If there are some questions I'll try to help, never touched Objective-C before 🤣 

@TimOliver Can you also adapt these files and the build phase so these errors don't appear anymore or is it an issue caused by cocoapods?

**Comment by beks6** [comment] 2017-04-20 18:23
For the sake of completeness.

After updating today to TOSMBClient v1.0.7  (look #48)  it wasn't necessary anymore to make the manual adaptions, my code builds so far without errors.

**Comment by TimOliver** [comment] 2017-04-20 18:45
Cool! Good to hear! Looks like it just needed a proper update to the latest codebase version. :)

This should hopefully fix the issue in Xcode 8.2 as well (Although you should always update to the latest Xcode as soon as possible. :) ), so I'll close this issue.

**Closed as completed by TimOliver** 2017-04-20 18:45 UTC
